config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :quizzs, only: [:index, :show] do
    resources :questions, only: [:show]
  end

  resources :answer_users, only: [:create]
  resources :users, only: [:index]

  root 'quizzs#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :proposition, presence: true
  validates :good_not_good, inclusion: { in: [true, false] }
end

app/models/answer_user.rb
class AnswerUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quizz
  has_many :answers, dependent: :destroy

  validates :sujet, presence: true
end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
  belongs_to :user
  has_many :questions, dependent: :destroy

  validates :theme, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :quizzs
  has_many :answer_users
  after_create :set_default_name

# Methode a écrire pour calculer le score total des users
# 3 options
    #Option A: Abandonner le stockage des reponses d'un user et le calcul du score a aprtir de là
    # et juste ajouter le score de la session a un champs score à créer (migration)
    #Option B: Forcer le sign-in dès le début (pas possible de jouer sans compte!) et utiliser la méthode total score pour calculer le score des users
    #Option C: Stocker en session le score d'une session sans sign-up, l'ajouter à un champ user.temporary_score et calculer le total score avec la fonction total_score + temporary_score


  def total_score


    total_score = 0

    # Quizz.all.each do |quizz|
    #   quizz.questions.each do |question|
    #     question.answers.each do |answer|
    #       if (answer.good_not_good && answer.proposition == AnswerUser.where(answer_id = answer.id))
    #         total_score += 1
    #       end
    #     end
    #   end
    # end

    # on recupere toutes les reponses de l'utilisateur
    answers_of_user = AnswerUser.where(user_id: self.id)

    # on verifie toutes celles qui sont justes
    answers_of_user.each do |answer|
      if Answer.find(answer.answer_id).good_not_good
        total_score += 1
        # on augmente le score de 1 a chaque reponse juste
      end
  end

    return total_score
  end

    # Do not work if user has not been signed in during the quizz

  def set_default_name
    self.name = email.split("@").first.split('.').first.capitalize
    save
  end


end

app/controllers/answer_users_controller.rb
class AnswerUsersController < ApplicationController

  def create
    # faire un test pour vérifier que le joueur a répondu
    # si il a répondu params[:answer_user] est remplie
    # on execute le boue de code

    # Il faut permettre l'enregistrement de la reponse même si elle est vide
    if params[:answer_user] # veut dire si les params  de la reponse sont present
      @answer_user = AnswerUser.new
      @answer_user.answer = Answer.find(params[:answer_user][:answer_id])
      @answer_user.user = current_user
      @question = @answer_user.answer.question
      @quizz = @question.quizz

      if @answer_user.save # si la reponse de l'utilisateur est sauvegardée.
        compute_score(@answer_user)
        session[@quizz.theme.to_sym]["questions_done"] << @question.id
        session[:counter] += 1
        redirect_to quizz_path(@quizz)
      else
        redirect_to question_path(@answer_user.answer.question)
      end
    else
      redirect_to users_path
    end
  end

  private

  def answer_user_params
    params.require(:answer_user).permit(:answer_id)
  end

  def compute_score(answer_user)
    if answer_user.answer.good_not_good == true
      session[:score] += 1
    end
  end

end


#AJAX ( si je prend l'option le compte a rebourg = la duree d'une partie, IL FAUT RAJOUTER LE REMOTE TRUE  A LA BONNE PLACE)

# if @answer_user.save
#       respond_to do |format|
#         format.html { redirect_to question_path(@answer_user.answer.question) }
#         format.js  # <-- will render `app/views/reviews/create.js.erb`
#       end
#     else
#       respond_to do |format|
#         format.html { render 'quizzs/:id' }
#         format.js  # <-- idem
#       end
#     end
#   end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: [ :show]

  def index
    @questions = Question.all
  end

  def show
# Voir la question 1
# Voir les differentes reponses associé
    @answers = @question.answers
    @answer_user = AnswerUser.new
  end


  # def new
  #   @question = Question.new
  # end

  def create

  end

  def update

  end

  def delete

  end


  private

  def find_quizz
    @quizz = Quizz.find(params[:quizz_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def quizz_params
    params.require(:question).permit(:sujet)
  end

end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController

  before_action :find_quizz, only: [ :show ]


  def index
    # Elie : Rendre disponible l'ensemble des resources pour une partie
    @quizzs = Quizz.all
    session[:score] = 0
    session[:counter] = 0
  end

  def show
    # MAX TROUVER DANS TOUTES LES QUESTIONS DU QUIZZ UNE QUESTION PAS DEJA FAITES
    @question = select_random_question
    if @question.nil?
      redirect_to users_path
    else
      @answers = @question.answers # je veux afficher les answers de la question ci dessu
      # Elie dans cette vue le joueur va cree la reponse à la question
      @answer_user = AnswerUser.new
      @score = session[:score]

    end
  end


  private

  def find_quizz
    @quizz = Quizz.find(params[:id])
  end

  def quizz_params
    params.require(:quizz).permit(:theme)
  end


  def select_random_question
    # MAX 1ere question je récupere tous les ids / questions suivantes je connais deja les ids donc pas besoin de faire une requete
    if session[:counter] == 0
      session[@quizz.theme.to_sym] = {} # creation
      session[@quizz.theme.to_sym]["quizz_questions"] = @quizz.questions.map {|question| question.id}
      session[@quizz.theme.to_sym]["questions_done"] = []
      @quizz_questions = session[@quizz.theme.to_sym]["quizz_questions"]
      @done_questions = session[@quizz.theme.to_sym]["questions_done"]
      @questions_to_do = @quizz_questions
    else
      @quizz_questions = session[@quizz.theme.to_sym]["quizz_questions"]
      @questions_to_do = @quizz_questions
      @done_questions = session[@quizz.theme.to_sym]["questions_done"]
      @done_questions.each do |done_question|
      @questions_to_do.delete(done_question)
      end
    end
    if @questions_to_do.any?
      @random_question_id = @questions_to_do.sample
      @question = Question.find(@random_question_id.to_i)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index

    @users = User.all.flatten.sort! { |a,b| a.total_score <=> b.total_score }.reverse!

    # users => le classement des utilisateurs
    @score = session[:score]
  end

end

app/helpers/answer_users_helper.rb
module AnswerUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>M</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


</head>
<body>

<%= render 'shared/flashes' %>


<%= yield %>
<!-- En dessou du yield pour chargement rapide de la page -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/quizzs/index.html.erb
<!-- selection des quizz -->


<div class="container text-center padded">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 marmiton-card">
      <span class="marmiton-prefix">Quizz <strong>from</strong></span> <%= render "shared/marmiton" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 first-card">
        <h3 class= "title-card" id="title-index-quizz">
          Dans quelle catégorie étés vous incollable?
        </h3>

        <% @quizzs.each do |quizz| %>
          <div class="col-md-6">
            <div class="plate">
              <%= link_to quizz.theme, quizz_path(quizz) %>
            </div>
          </div>
        <% end %>
         <div>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "btn btn-danger btn-lg") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: "btn btn-success btn-lg")  %>
        <% end %>
      </div>
    </div>
  </div>
</div>








<!--   <div class="container first-card">
    <div class="row">
      <div class="col-xs-9 col-md-offset-3 ">
        <div class="container second-card">
         <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <h2>Dans quelle catégorie étés vous incollable?</h2>
          </div>
        </div>
        </div>
        <div class="container fird-card">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <ul>
                <% @quizzs.each do |quizz| %>
                <li><%= link_to quizz.theme, quizz_path(quizz) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> -->

app/views/quizzs/show.html.erb
<!--  vue : repondre aux questions -->

<div class="container padded">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 marmiton-card text-center">
      <span class="marmiton-prefix">Cuisine <%= @question.quizz.theme %> <strong>from</strong></span> <%= render "shared/marmiton" %> <span class="label label-success label-score"><%= @score %> pts</span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3" style="padding: 0;">
      <div class="first-card">
        <div class="question-show-quizz">
          <h3><%= @question.sujet %></h3>
        </div>
        <div id="answer-show-quizz">
          <%= simple_form_for @answer_user do |f| %>
            <%= f.input :answer_id, collection: @answers.map { |answer| [answer.proposition, answer.id] }, as: :radio_buttons, label: "Votre réponse", :checked => @answers.first %>
            <div id="answer-btn"><%= f.submit "confirmer", :class => "btn btn-danger"%></div>
          <% end %>
        </div>
        <div class="countdown" id="timer"></div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_marmiton.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="marmiton" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 177 35" enable-background="new 0 0 177 35" xml:space="preserve">
<g>
  <path fill="#ED6E25" d="M60.7,34.8v-2c-1.3,1.6-2.8,2.2-5,2.2c-0.6,0-1.2-0.1-1.8-0.2s-1.1-0.3-1.7-0.6C46,31,46,22.3,49.5,16.9
    c0.7-0.9,1.6-1.6,2.7-2.2c0.5-0.3,1.1-0.5,1.7-0.6c0.6-0.1,1.2-0.2,1.8-0.2c2.2,0,3.6,0.6,5,2.2c0.4-0.9,1.3-1.8,2.7-1.8
    c1.7,0,2.9,1.3,2.9,3v17.6h-5.7C60.7,34.9,60.7,34.8,60.7,34.8z M52.6,24.6c-0.1,2.3,1.2,4.6,3.9,4.8c0.6,0,1.2-0.1,1.7-0.4
    c1.5-0.7,2.3-2.5,2.3-4.6s-0.8-3.8-2.3-4.6c-0.5-0.2-1.1-0.4-1.7-0.4C53.6,19.7,52.5,22.3,52.6,24.6L52.6,24.6z"/>
  <path fill="#ED6E25" d="M68.9,34.8V17.2c0-1.7,1.2-3,2.9-3c1.5,0,2.5,1,2.9,1.8c1-1.1,2.4-2.2,4.1-2.2c1.5,0,2.9,1.2,2.9,3
    c0,2-1.5,2.5-3.6,3.1c-2.5,0.7-3.3,1.4-3.3,4.4v10.3h-5.9V34.8z"/>
  <path fill="#ED6E25" d="M107.3,34.8V22.3c0-1.8-1-3.6-2.9-3.6c-1.9,0-2.9,1.7-2.9,3.6v12.5h-5.9V22.3c0-1.8-1-3.6-2.9-3.6
    c-1.9,0-2.9,1.7-2.9,3.6v12.5h-5.7V17.2c0-1.7,1.2-3,2.9-3c1.5,0,2.5,1,2.9,1.8c0.9-1.4,2.9-2.2,5-2.2c1.7,0,4,0.6,5.4,2.4
    c1.4-1,3.1-2.4,5.7-2.4c4.1,0,7.2,2.1,7.2,6.9v14.1L107.3,34.8L107.3,34.8z"/>
  <path fill="#ED6E25" d="M118.5,5.5c1.9,0,3.4,1.5,3.4,3.4s-1.5,3.4-3.4,3.4c-1.9,0-3.4-1.5-3.4-3.4S116.7,5.5,118.5,5.5L118.5,5.5z
     M115.7,34.8V17.2c0-1.7,1.2-3,2.9-3c1.7,0,2.9,1.3,2.9,3v17.6H115.7z"/>
  <path fill="#ED6E25" d="M157,24.3c0,5.9-4,10.7-9.9,10.7c-5.9,0-9.9-4.7-9.9-10.7s4-10.7,9.9-10.7C153.1,13.8,157,18.5,157,24.3
    L157,24.3z M143,24.3c0,2.7,1.4,5,4,5s4-2.2,4-5c0-2.7-1.4-5-4-5C144.6,19.5,143,21.7,143,24.3L143,24.3z"/>
  <path fill="#ED6E25" d="M159,34.8V17.2c0-1.7,1.2-3,2.9-3c1.5,0,2.5,1,2.9,1.8c0.9-1.4,2.5-2.2,5-2.2c4.1,0,7.2,2.1,7.2,6.9v14.1
    h-5.8V22.3c0-2-1.2-3.6-3.2-3.6c-2,0-3.2,1.5-3.2,3.6v12.5L159,34.8L159,34.8z"/>
  <path fill="#ED6E25" d="M133.8,14.4h-1.6v-3.9c0-1.7-1.2-3-2.9-3c-1.7,0-2.9,1.3-2.9,3v4c-1.2,0.3-2,1.1-2,2.6c0,1.5,0.8,2.3,2,2.6
    v15h5.9V19.9h1.6c1.8,0,3-0.8,3-2.7C137,15.2,135.6,14.4,133.8,14.4z"/>
  <g>
    <path fill="#ED6E25" d="M16.5,18.7c-1.9,0-2.9,1.7-2.9,3.6v12.5h5.8V22.2C19.5,20.4,18.5,18.7,16.5,18.7z"/>
    <path fill="#ED6E25" d="M28.3,18.7c-1.9,0-2.9,1.7-2.9,3.6v12.5h5.9V22.2C31.2,20.4,30.2,18.7,28.3,18.7z"/>
    <path fill="#ED6E25" d="M44.1,13.1c-0.9,0.2-1.8,0.4-2.7,0.4c-0.5,0-0.9-0.1-1.4-0.2c-1.4-0.3-2.6-1-3.6-2.1
      c-0.4-0.5-0.8-1-1.1-1.5c-2.4,0.7-5.3,0-7-2c-1-1.2-1.6-2.6-1.7-4.2c-1.6,0.9-3.6,0.6-4.9-0.8c-0.1-0.2-0.3-0.3-0.4-0.5
      c-1.4,1.4-3.3,2.3-5.5,2.3c-3,0-5.7-1.8-6.9-4.5c-3.2,0.4-6,2.6-7.2,5.5C1.4,6,1.2,6.6,1.1,7.2C-0.2,16.4-0.5,25.6,1,34.7h7.1
      V17.1c0-1.7,1.2-3,2.9-3c1.5,0,2.5,1,2.9,1.8c0.9-1.4,2.9-2.2,5-2.2c1.7,0,4,0.6,5.4,2.4c1.4-1,3.1-2.4,5.7-2.4
      c4.1,0,7.3,2.1,7.3,6.9v14.1h6.9C44.8,27.4,44.8,20.3,44.1,13.1z"/>
  </g>
</g>
</svg>

app/views/users/index.html.erb
<!-- vue : tableau de classement -->


<div class="container padded">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 marmiton-card text-center">
      <span class="marmiton-prefix">Cuisine italienne <strong>from</strong></span> <%= render "shared/marmiton" %> <span class="label label-success label-score"><%= @score %> pts</span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 first-card text-center" style="padding: 30px;">
          <div>
            <h3 class= "title-card" id="title-index-user"> Classement</h3>
          </div>
          <div class="question-show-quizz">
            <p>Félicitation, votre score est de : <%= @score%> POINTS </p>
            <% if current_user %>
            <p>Votre total de points est de <%= current_user.total_score %>.</p>
            <% else %>
            <p>Inscrivez vous pour cumulez vos points et tenter de gagner des repas dans les meilleures restaurant ! </p>
            <% end %>
          </div>
            <div>
            <% if user_signed_in? %>

              <%= link_to('Deconection', destroy_user_session_path, :method => :delete, class: "btn btn-danger" ) %>

            <% else %>

              <%= link_to('Connection', new_user_session_path, class: "btn btn-success")  %>

            <% end %>
             <%= link_to('Quizzine', quizzs_path(@quizz), class: "btn btn-success")  %>
          </div>

          <div class="container" id="answer-show-quizz">
            <p>Le tableau des High Score!</p>
            <div class="row">
              <div class="col-xs-6">
                <ul class="list-unstyled text-center">
                  <% @users.each do |user| %>
                    <li class="text-left"><%= user.name %> :</li>
                  <% end %>
                </ul>
              </div>
              <div class="col-xs-6">
                <ul class="list-unstyled text-center">
                  <% @users.each do |user| %>
                    <li class="text-right"><%= user.total_score %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>



      </div>
    </div>
  </div>